# Configuration de la connexion à MariaDB
mariadb:
  host: "localhost"
  port: 3306
  database: "rivrs"
  user: "root"
  password: ""

# Configuration de RabbitMQ
rabbitmq:
  host: "localhost"
  port: 5672
  username: ""
  password: ""
  virtualhost: ""

# Configuration du jeu
game:
  points_interval: 20 # Intervalle en ticks pour l'incrémentation des points

messages:
  HOLOGRAM_NAME: "<red>Your score: <yellow>%count%"