name: RivrsTest
version: '1.0-SNAPSHOT'
main: fr.yanis.rivrs.RMain
api-version: '1.20'
authors: [ YanisB ]
website: https://yanis-benyacine.fr
depend:
  - ProtocolLib

commands:
  setpos:
    description: Définit la postion x de la cuboid
    usage: /setpos [1|2]
    permission: rivrs.admin.setpos
  createzone:
    description: Crée une cuboid
    usage: /createzone <name>
    permission: rivrs.admin.createzone
  count:
    description: Ajoute un nombre de score à un joueur
    usage: /count <player> <number>
    permission: rivrs.admin.count

permissions:
  rivrs.admin.setpos:
    description: Permet de définir la position x de la cuboid
    default: op
  rivrs.admin.createzone:
    description: Permet de créer une cuboid
    default: op
  rivrs.admin.count:
    description: Permet d'ajouter un nombre de score à un joueur
    default: op