name: RivrsTest
version: '1.0-SNAPSHOT'
main: fr.yanis.rivrs.RMain
api-version: '1.21'
authors: [ YanisB ]
website: https://yanis-benyacine.fr

commands:
  setpos:
    description: Définit la postion x de la zone
    usage: /setpos [1|2]
    permission: rivrs.admin.setpos

permissions:
  rivrs.admin.setpos:
    description: Permet de définir la position x de la zone
    default: op